export const CREATE_PLAN_REQUEST = "CREATE_PLAN_REQUEST";
export const CREATE_PLAN_SUCCESS = "CREATE_PLAN_SUCCESS";
export const CREATE_PLAN_FAILURE = "CREATE_PLAN_FAILURE";

export const UPDATE_PLAN_REQUEST = "UPDATE_PLAN_REQUEST";
export const UPDATE_PLAN_SUCCESS = "UPDATE_PLAN_SUCCESS";
export const UPDATE_PLAN_FAILURE = "UPDATE_PLAN_FAILURE";

export const GET_PLAN_REQUEST = "GET_PLAN_REQUEST";
export const GET_PLAN_SUCCESS = "GET_PLAN_SUCCESS";
export const GET_PLAN_FAILURE = "GET_PLAN_FAILURE";

export const DELETE_PLAN_REQUEST = "DELETE_PLAN_REQUEST";
export const DELETE_PLAN_SUCCESS = "DELETE_PLAN_SUCCESS";
export const DELETE_PLAN_FAILURE = "DELETE_PLAN_FAILURE";

export const CREATE_SUBPLAN_REQUEST = "CREATE_SUBPLAN_REQUEST";
export const CREATE_SUBPLAN_SUCCESS = "CREATE_SUBPLAN_SUCCESS";
export const CREATE_SUBPLAN_FAILURE = "CREATE_SUBPLAN_FAILURE";

export const UPDATE_SUBPLAN_REQUEST = "UPDATE_SUBPLAN_REQUEST";
export const UPDATE_SUBPLAN_SUCCESS = "UPDATE_SUBPLAN_SUCCESS";
export const UPDATE_SUBPLAN_FAILURE = "UPDATE_SUBPLAN_FAILURE";

export const GET_SUBPLAN_REQUEST = "GET_SUBPLAN_REQUEST";
export const GET_SUBPLAN_SUCCESS = "GET_SUBPLAN_SUCCESS";
export const GET_SUBPLAN_FAILURE = "GET_SUBPLAN_FAILURE";

export const DELETE_SUBPLAN_REQUEST = "DELETE_SUBPLAN_REQUEST";
export const DELETE_SUBPLAN_SUCCESS = "DELETE_SUBPLAN_SUCCESS";
export const DELETE_SUBPLAN_FAILURE = "DELETE_SUBPLAN_FAILURE";

export const SET_ACTIVE_SIMULATION_ITEM = "SET_ACTIVE_SIMULATION_ITEM";

export const GET_SOURCE_SEQUENCE_REQUEST = "GET_SOURCE_SEQUENCE_REQUEST";
export const GET_SOURCE_SEQUENCE_SUCCESS = "GET_SOURCE_SEQUENCE_SUCCESS";
export const GET_SOURCE_SEQUENCE_FAILURE = "GET_SOURCE_SEQUENCE_FAILURE";

export const COPY_SEQUENCE_REQUEST = "COPY_SEQUENCE_REQUEST";
export const COPY_SEQUENCE_SUCCESS = "COPY_SEQUENCE_SUCCESS";
export const COPY_SEQUENCE_FAILURE = "COPY_SEQUENCE_FAILURE";


export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILURE = "CREATE_COMMENT_FAILURE";

export const GET_COMMENT_REQUEST = "GET_COMMENT_REQUEST";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_FAILURE = "GET_COMMENT_FAILURE";

export const UPDATE_COMMENT_REQUEST = "UPDATE_COMMENT_REQUEST";
export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_FAILURE = "UPDATE_COMMENT_FAILURE";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE";

export const SET_OBJECTS_REQUEST = "SET_OBJECTS_REQUEST";
export const SET_OBJECTS_SUCCESS = "SET_OBJECTS_SUCCESS";
export const SET_OBJECTS_FAILURE = "SET_OBJECTS_FAILURE";

export const SELECT_OBJECTS_REQUEST = "SELECT_OBJECTS_REQUEST";
export const SELECT_OBJECTS_SUCCESS = "SELECT_OBJECTS_SUCCESS";
export const SELECT_OBJECTS_FAILURE = "SELECT_OBJECTS_FAILURE";

export const UPLOAD_TEMPLATE_REQUEST = "UPLOAD_TEMPLATE_REQUEST";
export const UPLOAD_TEMPLATE_SUCCESS = "UPLOAD_TEMPLATE_SUCCESS";
export const UPLOAD_TEMPLATE_FAILURE = "UPLOAD_TEMPLATE_FAILURE";

export const EXPORT_TEMPLATE_REQUEST = "EXPORT_TEMPLATE_REQUEST";
export const EXPORT_TEMPLATE_SUCCESS = "EXPORT_TEMPLATE_SUCCESS";
export const EXPORT_TEMPLATE_FAILURE = "EXPORT_TEMPLATE_FAILURE";

export const SET_SIMULATION_DATE_RANGE = "SET_SIMULATION_DATE_RANGE";